### ISSUE TITLE
Note in `h.tests.tsx`

### ISSUE THREAD

**Issue by mindplay-dk** [jorgebucaran/patchdom#77]
@andrewiggins what's this note about?

https://github.com/picodom/picodom/blob/acfe0c875136da6119c8672aa66430b250a4651f/test/typings/h.test.tsx#L61

As far as I can tell, the example following that line is fine? it shouldn't fail?

If you intended to have something there that *should* fail, the test-harness wouldn't work, since it's just trying to compile the file and doesn't make any assertions about errors emitted by the compiler, as far as I can tell?

**Comment by andrewiggins** [comment]
Correct, the test harness doesn't yet check that the proper errors are thrown. For the time being I just commented the lines out and left that note as a reminder to manually test those lines.

Perhaps the comment should read "when uncommented, ..."

I had a prototype of error tests I never finished to assert errors were thrown properly but I never quite got it to a place I thought was long term maintainable. Probably need to revisit it again.

**Comment by jorgebucaran** [comment]
Tagged as invalid as I am no longer using this file! Thank you all.
