### ISSUE TITLE
Debug SVG attributes 

### ISSUE THREAD

**Issue by mindplay-dk** [jorgebucaran/patchdom#80]
Basically just apply these changes from Hyperapp:

https://github.com/hyperapp/hyperapp/commit/4f147c2ec00fd2a69b2298981a81372c603211ca#commitcomment-26628985

**Comment by JorgeBucaran** [comment]
In Hyperapp, after that 4f147c2, SVG attributes are never set as properties, so:

```js
element[name] = value == null ? "" : value
```

...will never run. What do you mean by opening this issue?

**Comment by mindplay-dk** [comment]
> What do you mean by opening this issue?

Just that we should apply the same change to Picodom - I think SVG attributes are currently not working?

**Comment by JorgeBucaran** [comment]
@mindplay-dk Will do! Please give me a few days. 🙏

**Comment by mindplay-dk** [comment]
@JorgeBucaran I can take a pass at porting the changes tomorrow morning - I'll submit a PR! 👍

**Comment by jorgebucaran** [comment]
Applied.
