### ISSUE TITLE
Patch prepends result to parent.

### ISSUE THREAD

**Issue by rbiggs** [jorgebucaran/patchdom#92]
By default the patch method prepends the result to the parent element. This means that if you have a page rendered on the server with some default content and then use path on the parent element, Pidocom prepends using `element.insertBefore`. Case in view, say you have a header with title, menu, etc. rendered on the server and then try to use patch to inject content into the document body at load time. Picodom prepends that content before the header, pushing it down. The only way to avoid this as it stands is to always use empty containers with patch. This seams very wasteful. It would be nice if the insertion behavior followed norms that developers expect so they aren't scratching their heads when things are prepended. 
Otherwise, hey Jorge, good job on this project.

**Comment by JorgeBucaran** [comment]
> It would be nice if the insertion behavior followed norms that developers expect so they aren't scratching their heads when things are prepended.

We inherited his behavior from Hyperapp. In Hyperapp if your container has existing content in it, we attempt to hydrate it, but there is none in Picodom, so there's no reason we shouldn't let you insertElement, appendChild or replaceElement if that's what you want. I'll look into this and have a solution for the 2.0.0 release.

**Comment by mindplay-dk** [comment]
This might be mitigated also by the change proposed [here](https://github.com/picodom/picodom/issues/89#issuecomment-356752718) in #89 - for the top-most call to `patch`, order would not be an issue or a concern at all, since the caller would be responsible for designating exactly the element they want to patch; it's order wouldn't be affected at all.

**Comment by rbiggs** [comment]
So, looking at earlier versions of Picodom, I noticed that it used to have a different call signature: 
```javascript
function patch(parent, element, oldNode, node, isSVG, nextSibling) {
  if (oldNode == null) {
    element = parent.insertBefore(createElement(node, isSVG), element)
  }
...
}
```
The way `insertBefore` works is like this:

```javascript
Node.insertBefore(newNode, referenceNode)
```
If `referenceNode` is undefined, `insertBefore` appends the new node to the target, otherwise it prepends it before the reference node. With the older call signature, during the first render `element` was always undefined. This meant that `patch` always appended during first run. 

Now you have the following call signature:

```javascript
export function patch(parent, oldNode, newNode) {
  var element = patchElement(parent, parent.children[0], oldNode, newNode)

  for (var cb; (cb = callbacks.pop()); cb()) {}

  return element
}
```
Because you pass in `parent.children[0]`, the first render will always prepend to whatever that first child element is in the target element. I suppose you could try to test if the parent already has children or not. Maybe I'll give that a try and see, unless @JorgeBucaran has some other idea about how to deal with this.

**Comment by JorgeBucaran** [comment]
@rbiggs Can you write some pseudocode of how you intended to use picodom exactly?

**Comment by rbiggs** [comment]
OK. Here's some links on Codepen. This is based on the discussion I was having with Mindplay about a class-based component using Picodom. My first attempt is here: https://codepen.io/rbiggs/pen/RxBKRq?editors=1010. In this pen I'm rendering two list components into the same container (section tag). This also highlights the prepend problem. The static markup h2 that should be at the top gets pushed down last. Since I rendered two list components into the same section tag, the first list became the last list. The correct order for the content should be h2, fruit list, pet list. Everything came out backwards. 

By the way, the Component class uses Picodom's `patch`function inside its `update` method. The Component class uses `this.element` to keep track of the render tree. You can use this for query searches, like `ref` in React, registering events, etc.

I was expecting that updating the two lists should work since they both have separate state. However, what happens is when adding a new item to either list, Picodom only patches the first list in the DOM. I'm pretty sure that's because of using `parent.children[0]` to determine what to patch. Of course, if you were only ever patching one component in a container element, this would not be a problem. 

I started digging around in the commit history and I discovered that you had simplified the call signature at version 1.0.0. In version 0.2.0 the patch call signature was `function(oldNode, node, element, parent, cb)`.   So I took the previous Codepen and updated it to use version 0.2.0 and I refactored the Component class update function to pass its `this.element` reference as the element argument. Surprisingly this works as I would have expected: https://codepen.io/rbiggs/pen/ppZRWE?editors=1010. You will notice that it doesn't prepend the content but appends it as expected. The lists are also added in the correct order, fruits first, pets last. And adding an item to either list results in the correct tree being updated. That's because element is a reference to the rendered tree. 

I'm not sure why you decided to drop that, other than purely for simplifying the call signature. Seems like that reduced the ability of Picodom to determine accurately what it needs to update when the container has pre-existing content. For what I was trying to do it looks like 0.2.0 is the better version of Picodom for accurate patching. Don't take that negatively. As it is, Picodom can fill the needs for people taking a more functional approach using a render function wrapper. If you have only one render/patch and the rest of your app is functional components, no problem.

**Comment by jorgebucaran** [comment]
@rbiggs In the new API:

```jsx
import { h, patch } from "patchdom"

document.body.appendChild(
  patch( h("h1", {}, "Hello") )
)
```

The patch function now returns an element, if none is given, allowing you to append it to a container if that's what you want. If you pass an existing element instead, patchdom will patch **that** element (attempting to recycle any existing markup), instead of using it as a container like in the past.
