### ISSUE TITLE
VNode compatibility with Hyperapp 1.1

### ISSUE THREAD

**Issue by zaceno** [jorgebucaran/patchdom#93]
Since hyperapp 1.1 changed the spec for virtual doms (`attributes` instead of `props` et c), I suggest we change Picodom to match.

Unless there's a particular reason for Picodom and Hyperapp to diverge, it seems like a good idea to keep them as compatible as possible, so that tools that produce or operate on vnodes can be compatible with both (such as Hyperapp-transitions). Also, I presume whatever the reasons for Hyperapp to change (Preact compat?) are as valid for Picodom.

**Comment by jorgebucaran** [comment]
Fixed!
