### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/patchdom#95]
Change name because of name collision with @hville's pico-dom.

@hville was first, so maybe we should fail in his favor. It's a shame to lose the logo though 😕

**Comment by brodybits** [comment]
> Change name because of name collision with @hville's pico-dom.

Looks not active. From <https://github.com/hville/pico-dom/issues/1#issuecomment-359628668>:
> Pico-dom was an experiment at an alternative template-based scripts. It works but it quickly gets confusing as to what is a template and what is a component. Interesting but Abandoned.

**Comment by JorgeBucaran** [comment]
@brodybits Oh, interesting discovery. I should have looked into the issues. Thanks! 🎉

**Comment by JorgeBucaran** [comment]
I'd like to reopen and reconsider a name change based on the following:

- I've decided to remove the org and move picodom into my own username.
- After I rewrite the diff algo (few months from now) we may no longer be 1kB, hopefully still less than 2kB, though. At that point, tiny size might not be picodom's most distinctive feature.

**Comment by mindplay-dk** [comment]
> At that point, tiny size might not be picodom's most distinctive feature

I don't think it's the *most* distinctive feature now? The main attraction for me is element-level life-cycle events. That's where Picodom deviates from other JSX libs conceptually. I'm honestly not interested in marginal byte-size savings or minor differences in terms of a single API point that most apps are going to invoke around once or so.

On the name topic, I think the name is great, the logo is nice, and there's no real issue with ambiguity versus an older, dead library - the new Picodom is already making a name for itself. I'd say keep it :-)

**Comment by jorgebucaran** [comment]
Renamed to **patchdom**. 🎉
