### ISSUE TITLE
Name change broke Codepen pens

### ISSUE THREAD

**Issue by rbiggs** [jorgebucaran/patchdom#99]
All the Codepen pens that were using https://unpkg.com/picodom or https://unpkg.com/picodom@latest are currently broken due to the name change. At this point this means the vast majority are broken. Surprisingly, I have two pens that use specific versions of picodom and those still work. By the way, https://unpkg.com/patchdom doesn't seem to work. Unpkg.com says the package doesn't exist.

**Comment by rbiggs** [comment]
Thanx, otherwise, congrats on the major upgrade.

**Comment by mindplay-dk** [comment]
`picodom.js.org` is down as well - you might want to make sure it redirects? with the correct status code - or you'll lose the juice. A lot of links and bookmarks out there already.

**Comment by rbiggs** [comment]
hmmm... problem want to rename the Redit.com/r/picodom as well.

**Comment by jorgebucaran** [comment]
@rbiggs Can't on reddit. 😓
